### ISSUE TITLE
Duplictae "row.names" not allowed

### ISSUE THREAD

**Issue by mctruebasanchez** [DavidGZ1/HowDirty#11]
Hello! 

When using: get_annotation_template(file_report_skyline = "PeakAreas_Contaminants.csv", save="TRUE")
I get an error from read.table saying: "duplicate 'row.names' not allowed. 

If I understood the tutorial properly, PeakAreas_Contaminants.csv is a CSV file with the following columns; Protein, Peptide, Replicate name, peptide retention time, Total Area MS1 and Total Ion current Area. 

With this file there will be always duplicated row.names if the contaminant is found in many samples. How could I solve this?

**Comment by DavidGZ1** [comment]
Hi Maria Cristina,
Thanks for trying HowDirty. I need more information to reproduce and fix the issue.
1. Did you export the PeakAreas_Contaminants.csv file from Skyline following the instructions of the tutorial? 
2. Could you share an example file resulting in the error?
3. Do you have the same problem when using the [example file](https://github.com/DavidGZ1/HowDirty/blob/main/example/data/PeakAreas_Contaminants_2021-231.csv)?

The file should contain these columns: "Proteins", "Peptides", "Replicate Name", "Peptide Retention Time", "Total Area MS1", "Total Ion Current Area". Please check that the headers are exactly those,  with the same capitalization and the "s" at the end of Proteins and Peptides, but without quotation marks.
If there is another column before Proteins, it may be that R is recognizing it as row.names, which could create the problem. If that is the case, try reordering the columns as mentioned above.

Best regards,
David

**Comment by mctruebasanchez** [comment]
Hi David, 
Thank you very much for your help. 

I think I have more than one problem: 
 
Yes, I exported the file following the instructions on the tutorial. Indeed my columns were named "Protein" and "Peptide", without the s at the end. I find it weird as I exported exactly as in the tutorial. I have doubled checked the parameters in Document settings/report but it exports it without the s still. Could I fix this or I just need to change it manually?
![image](https://github.com/DavidGZ1/HowDirty/assets/75306553/22126326-3a81-4099-9fab-8ef24de12284)

Now I have fixed that and I have this file: 
[PeakAreas_Contaminants.csv](https://github.com/DavidGZ1/HowDirty/files/12585921/PeakAreas_Contaminants.csv)

Which is very similar to the example you sent, but still having an error: 
Error in read.table(file = file, header = header, sep = sep, quote = quote,  : 
  more columns than column names

Note that I did not have the error with your example file. It was run and save properly: 

ReplicateNameSkyline names obtained from the input. Please update Sample and Condition columns.
samples_annotation_template.csv saved to  D:/R_Projects/HowDirty/ZH03

Maybe I have missed something on how to export the file? I am using Skyline 22.2.0.527

**Comment by DavidGZ1** [comment]
Hi Maria Cristina,
Thank you for the details and for sharing your file. I released a patched version (v0.2.1) to solve the issue with loading the semicolon-separated file (point 1 below). Please reinstall HowDirty and try again using the file directly exported from Skyline. You can keep the column names “Protein” and “Peptide”, without “s” (point 2 below). 
remove.packages("HowDirty")
devtools::install_github("DavidGZ1/HowDirty", force = TRUE)

1. It looks like you are using a computer with European configuration for decimals. Thus, Skyline generates csv files with semicolons instead of commas as value separators. I modified the functions used to load the data. It should work now for both types of files.

2. The columns "Proteins" and "Peptides" include an "s" at the end in Skyline but not in the csv exported. This is already the right input for HowDirty, there is no need to modify the column names manually. I also added a note about this in the tutorial.

Please let me know if this worked for you.
Best regards,
David

**Comment by mctruebasanchez** [comment]
Hi David, 

Indeed I work in Europe! I reinstalled the package with the commands you shared, but unfortunately it is still not working. I have the same error: 

get_annotation_template(file_report_skyline = "PeakAreas_Contaminants.csv", save="TRUE")
Error in read.table(file = file, header = header, sep = sep, quote = quote,  : 
  duplicate 'row.names' are not allowed


This is the file I am trying to read: 
[PeakAreas_Contaminants.csv](https://github.com/DavidGZ1/HowDirty/files/12657120/PeakAreas_Contaminants.csv)

I've noticed that there is one more column called "Height" that you didn't mention before, so I also tried to remove it and load it again, but still the error is the same. 
[PeakAreas_Contaminants_NoH.csv](https://github.com/DavidGZ1/HowDirty/files/12657158/PeakAreas_Contaminants_NoH.csv)

Something else that I've noticed is that my .csv open in excel loaded in columns, while your example file its loaded as in 'text'. This maybe due to the semi-colon or comma delimited issue you just mentioned but I wanted to note it just in case, 

![image](https://github.com/DavidGZ1/HowDirty/assets/75306553/c6c2159d-f436-4a3b-81c6-9adaf802855d)
![image](https://github.com/DavidGZ1/HowDirty/assets/75306553/d2bc6cc0-2ee1-470e-8b44-ddb8e426e0a0)

**Comment by DavidGZ1** [comment]
Hi Maria Cristina,
The Height column is not needed. It’s a leftover from a previous version of the workflow. It shouldn’t matter if it’s included or not in your file.
Yes, the behavior you see in Excel is most likely also due to the European decimal configuration. The current version of the code works well for me using an European computer where I changed this configuration already.
I can try to fix this issue next week. In the meanwhile, can you please try by changing the configuration of list separators in your computer, export the file from Skyline and try again with HowDirty?
You can follow the instructions below. Then, all csv files generated should be comma-separated. In general, this should avoid you having similar problems with other packages in R.
“Windows 8/10
To change regional settings,
•	go to Start > Control Panel > Regional and Language Options | Windows 10  (Start >type Control Panel  and press enter > Region) 
•	Click Additional Settings
•	For Decimal Symbol, enter a dot:.
•	For List Separator, enter a comma:,”
https://resrequest.helpspot.com/index.php?pg=kb.page&id=279

Best regards,
David
